### PR TITLE
translate to chinese

### PR DESCRIPTION
**Pull request by Goodahome**

### CODE REVIEW

**Comment by Goodahome** [comment]
I don'n know why it's doesn't work
image

**Comment by MGeurts** [comment]
You are not using the latest language files from [my repository](https://github.com/MGeurts/genealogy/tree/main/lang).

Import the latest language files from [my repository](https://github.com/MGeurts/genealogy/tree/main/lang) into[ your repository](https://github.com/Goodahome/genealogy/tree/main/lang).
Then compare all files in the ZN folder with those in the EN folder.
You'll see that person.contact and others are missing.

**Comment by MGeurts** [comment]
You can check your language files by running this command:

`php artisan translations:check --excludedDirectories=vendor`

Read : [https://github.com/LarsWiegers/laravel-translations-checker/](https://github.com/LarsWiegers/laravel-translations-checker/)

**Comment by MGeurts** [comment]
I have to REJECT this Pull Request because the Chinese language files are based on your old English language files and not on [my latest language files](https://github.com/MGeurts/genealogy/tree/main/lang).

Please add a new PR based on [my latest laguage files](https://github.com/MGeurts/genealogy/tree/main/lang).

Thank you.

**Pull request closed without merging**
